//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kaonavi.Net {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kaonavi.Net.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   SheetSerializable object &apos;{0}&apos; should be partial. Source generation will be skipped. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KAONAVI001_MessageFormat {
            get {
                return ResourceManager.GetString("KAONAVI001_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SheetSerializable object should be partial に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KAONAVI001_Title {
            get {
                return ResourceManager.GetString("KAONAVI001_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SheetSerializable object &apos;{0}&apos; should not be inner class. Source generation will be skipped. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KAONAVI002_MessageFormat {
            get {
                return ResourceManager.GetString("KAONAVI002_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SheetSerializable object should not be inner class に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KAONAVI002_Title {
            get {
                return ResourceManager.GetString("KAONAVI002_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SheetSerializable object &apos;{0}&apos; should implement ISheetData. Source generation will be skipped. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KAONAVI003_MessageFormat {
            get {
                return ResourceManager.GetString("KAONAVI003_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SheetSerializable object should implement ISheetData に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KAONAVI003_Title {
            get {
                return ResourceManager.GetString("KAONAVI003_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SheetSerializable object &apos;{0}&apos; already implements ISheetData.ToCustomFields(). Source generation will be skipped. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KAONAVI004_MessageFormat {
            get {
                return ResourceManager.GetString("KAONAVI004_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SheetSerializable object should not implement ISheetData.ToCustomFields に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KAONAVI004_Title {
            get {
                return ResourceManager.GetString("KAONAVI004_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SheetSerializable object &apos;{0}&apos; should have at least one property with CustomField attribute. Source generation will be skipped. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KAONAVI005_MessageFormat {
            get {
                return ResourceManager.GetString("KAONAVI005_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SheetSerializable object should have property with CustomField に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KAONAVI005_Title {
            get {
                return ResourceManager.GetString("KAONAVI005_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; property has duplicated CustomField(&apos;{1}&apos;) attribute with &apos;{2}&apos; property. Source generation will be skipped. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KAONAVI006_MessageFormat {
            get {
                return ResourceManager.GetString("KAONAVI006_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CustomField should be unique に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KAONAVI006_Title {
            get {
                return ResourceManager.GetString("KAONAVI006_Title", resourceCulture);
            }
        }
    }
}
